<?php include 'components/header.php'?>
	<section class="mian-banner">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-lg-8 col-12">
					<div class="mian-abbner-txt">
						<h1>Terms &  <span>Condition</span></h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum. suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>
						<button>Shop Now <img src="assets/images/circle-btn.jpg"></button>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section class="privacy container py-5"><div class="row pt-5"><div class="col-12"><h1>Terms & Condition</h1><hr><p>By accessing and using the website you expressly agree to the following conditions.</p><h2>INTELLECTUAL PROPERTY RIGHTS</h2><p>The contents of this site, including brands, logos, drawings, data, product or company names, texts, images, etc. are protected by intellectual rights and belong to the operator or entitled third parties.</p><h2>LIMITATION OF LIABILITY</h2><p>The information on the website is of a general nature. The information is not adapted to personal or specific circumstances, and can therefore not be considered as personal, professional or legal advice to the user.</p><p>The operator makes great efforts to ensure that the information made available is complete, correct, accurate and up-to-date. Despite these efforts, inaccuracies may occur in the information made available. If the information provided contains inaccuracies or if certain information on or via the site is unavailable, the operator will make the greatest possible effort to rectify this as soon as possible.</p><p>However, the operator cannot be held liable for direct or indirect damage resulting from the use of the information on this site.</p><p>If you should discover inaccuracies in the information made available via the site, you can contact the operator of the site.</p><p>The content of the site (including links) may be adapted, changed or supplemented at any time without notice or notice. The operator gives no guarantees for the proper functioning of the website and can in no way be held liable for a malfunction or temporary (un)availability of the website or for any form of damage, direct or indirect, that would result from the access or use the website.</p><p>Under no circumstances can the operator be held liable to anyone, directly or indirectly, in a special or other way, for damage attributable to the use of this site or of another site, in particular as a result of links or hyperlinks, including, without limitation, of all losses, work interruptions, damage to programs or other data on the computer system, of equipment, software or other of the user.</p><p>The website may contain hyperlinks to websites or pages of third parties, or refer to them indirectly. Placing links to these websites or pages in no way implies an implicit endorsement of their content. The operator expressly declares that it has no control over the content or other characteristics of these websites and can in no way be held liable for the content or characteristics thereof or for any other form of damage resulting from its use.</p><h2>APPLICABLE LAW AND COMPETENT COURTS</h2><p>Belgian law applies to this site. In the event of a dispute, only the courts of the judicial district in which the operator's registered office is located are competent.</p></div></div></section>

	<?php include 'components/footer.php';?>